# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IOTDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'In service'), (0, 'In maintenance'), (-1, 'Out of service')], default=1, help_text='Designates whether this monitoring device should be treated as active. Set this to "out of service" instead of deleting device.', verbose_name='device status')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='registration date')),
                ('begin_of_service', models.DateField(default=django.utils.timezone.now, verbose_name='begin of service')),
                ('end_of_service', models.DateField(blank=True, default=None, null=True, verbose_name='end of service')),
                ('position', geoposition.fields.GeopositionField(max_length=42, verbose_name='position')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='devices', related_query_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'IoT Devices',
                'verbose_name': 'IoT Device',
                'abstract': False,
            },
        ),
    ]
