# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iotapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOTRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Complete record'), (0, 'Empty record'), (-1, 'Loosy record')], default=0, verbose_name='record status')),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Please introduce the log time as UTC time.', verbose_name='log date')),
                ('device', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='records', related_query_name='devices', to='iotapi.IOTDevice', verbose_name='device')),
            ],
            options={
                'verbose_name': 'IoT Record',
                'abstract': False,
                'verbose_name_plural': 'IoT Records',
            },
        ),
    ]
