# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 02:20
from __future__ import unicode_literals

from django.db import migrations
import sysmoon.fields.measurements


class Migration(migrations.Migration):

    dependencies = [
        ('iotapi', '0002_iotrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotrecord',
            name='temperature',
            field=sysmoon.fields.measurements.MeasurementField(default=-9999.9999, null=True, verbose_name='Temperature'),
        ),
    ]
